- buddy_alloc.h
- tests.c
Useful utility to test whether all previous allocations have been freed before deleting everything.
> add is_empty interface

- buddy_alloc.h
- tests.c
> cpp interop changes - drop _Bool, use portable popcount and highest_bit_position implementations

- Makefile
- bench.c
- buddy_alloc.h
- tests.c
Add a first-fit malloc implementation that uses the buddy tree walk machinery. It's a bit faster than the optimal-fit malloc for small-sized requests.
$ make bench
cc -O2 bench.c -o bench
./bench
Starting test with alloc size [64].
Test took 10 seconds in total. Allocation: 8 freeing: 2
Starting test with alloc size [128].
Test took 5 seconds in total. Allocation: 4 freeing: 1
Starting test with alloc size [256].
Test took 3 seconds in total. Allocation: 2 freeing: 1
Starting test with alloc size [512].
Test took 1 seconds in total. Allocation: 1 freeing: 0
Starting test with alloc size [1024].
Test took 0 seconds in total. Allocation: 0 freeing: 0
Starting test with alloc size [2048].
Test took 1 seconds in total. Allocation: 1 freeing: 0
Starting test with alloc size [4096].
Test took 0 …
> Introduce buddy_malloc_firstfit, drop left_bias/optimal modes

- bench.c
- buddy_alloc.h
- tests.c
Repeated benchmarks show that the optimal malloc is faster.
> Drop the firstfit malloc.

- buddy_alloc.h
- tests.c
I'm trying to use this library in a linux kernel module for a device driver. I know this project is intended for c99 but kernel module prefers C90 coding style. I also compile this library in user space with a more restricted compiler warning following this page: https://airbus-seclab.github.io/c-compiler-security/. Most of the fix are warning on cast changes alignment, arith-conversion and sign-conversion. 
I send this for reference. You don't need to merge it if you think the changes are out of scope for this project.
> make #include header and fragmentation calculation optional 

- buddy_alloc.h
If we have a customized `BUDDY_PRINTF`, stdio.h can be ignored.
[test and bench](https://envs.sh/20m.txt)
> only include stdio.h when used

- buddy_alloc.h
as the title.
btw, why specify llvm version in makefile explicitly?
> macro to keep c++ name mangle

- buddy_alloc.h
In many places the power of two was calculated from a too small value.
Integers that are of size `size_t` may be wider that `unsigned int`. The expression `1u << order` is undefined for `order` >= `sizeof(unsigned int) * CHAR_BIT`.
Replace the instances of `1u << order` with an inline function that instead shifts a `((size_t)1)`.
This allows `order < sizeof(size_t) * CHAR_BIT`.
> Calculate the power of two for large exponents

- buddy_alloc.h
- tests.c
Related to #40 - this way users can build both free and allocated histograms of the state of the allocator or present it in any other way as they see fit.
> Make buddy_walk iterate free slots as well

- .github/workflows/codeql.yml
Github is deprecating node 16 actions - bump them to 20.
```
[Analyze (c-cpp)](https://github.com/spaskalev/buddy_alloc/actions/runs/8477240015/job/23227870489)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, github/codeql-action/init@v2, github/codeql-action/autobuild@v2, github/codeql-action/analyze@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> Bump codeql versions

- .gitignore
- README.md
- bench.c
- buddy_alloc.h
Tested manually right now as there is no readily available github action with the Pelles C toolchain.
> Support compiling with Pelles C

- .gitignore
- CMakeLists.txt
- tests.c
> Add cmake project for benchmark, fix tests compile warning on msvc

- buddy_alloc.h
- tests.c
Add `buddy_get_embed_at` and `buddy_get_embed_at_alignment` functions to get a handle to an embedded buddy allocator in an arena that was moved/copied/restored to a different address.
> Add buddy_get_embed_at function. Fixes #114.

- buddy_alloc.h
- tests.c
Implement change tracking for integration with libpvl. Use the `BUDDY_EXPERIMENTAL_CHANGE_TRACKING` macro to enable it.
> Implement change tracking for integration with libpvl

- .github/workflows/main.yml
> Drop amd64_arm from ci/cd until windows builder issue is fixed

- buddy_alloc.h
While looking for another bug and using buddy_can_shrink as a signal it turned out that it is not handling virtual slots properly.
> Fixed a bug in buddy_is_free that could prevent downsizing

- .gitignore
- bench.c
- tests.c
Issue #128 reported a potential problem with repeated up-sizing the allocator. Add tests for this in both the normal and embedded modes. Instead of running the check invariant function (which also works but is a lot more slower) use the fragmentation metric. The basis of reasoning here is that if the resize does not alter the allocated slots in any way then the fragmentation metric should not change either.
Also fixed some formatting nits while at it.
> Add repeated upsizing tests

- .github/workflows/main.yml
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Use actions/upload-artifact@v4

- buddy_alloc.h
- tests.c
> Fix a bug in the bitset_shift calculations, resulting in a corrupted state after downsizing the allocator

- buddy_alloc.h
- tests.c
To avoid errors on defined but not used static function.
> Guard buddy_tree_buddy with BUDDY_EXPERIMENTAL_CHANGE_TRACKING
